// <auto-generated />
namespace EFVP_Example.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_product_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_product_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201804040354399_add_product_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
